### PR TITLE
Typescript typings

### PR DESCRIPTION
**Pull request by samdenty**
Hey there, awesome work!

I've ported `@types/nedb` to give full type safety inside Typescript, along with autocompletion etc.

I've tested it the example provided in the README, but it's possible I've left some things out.

You can now do cool stuff like:

```ts
interface User {
  name: string
}

async function fetch(name: string) {
  const user = await store.users.findOne<User>({ name })
  // user now has the implied type "User"
}
```

Let me know what you think!

### CODE REVIEW

**Comment by bajankristof** [comment]
Hey,
Great job and thanks for contributing, right now I don't have much time, but as soon as I can, I will look at the definitions and leave some feedback for you! Thanks again for your time and effort!

**Comment by kristofbajan** [comment]
Hi again!
I was just checking out the code and it seems alright but there are a couple of things I would like change:

- `declare class Nedb extends...` this should be `class Datastore`, thus the exported value should also refer to `Datastore`
- DataStore should be Datastore since that's the way I (and the original module's author) defined it. That also applies to DataStoreOptions -> DatastoreOptions etc.
- `CursorCount` is declared but never used also I don't have such interface so it should be removed from the code
- In your code `load()` returns `void` whereas it actually returns `Promise<undefined>` (since we are doing some loading here)
- Also `create(...)` returns a Proxy in reality so it should be `Proxy<Datastore>` (or just `Datastore` that's fine too I guess)

**Comment by bajankristof** [comment]
Hi again!
I was just checking out the code and it seems alright but there are a couple of things I would like change:

- `declare class Nedb extends...` this should be `class Datastore`, thus the exported value should also refer to `Datastore`
- DataStore should be Datastore since that's the way I (and the original module's author) defined it. That also applies to DataStoreOptions -> DatastoreOptions etc.
- `CursorCount` is declared but never used also I don't have such interface so it should be removed from the code
- In your code `load()` returns `void` whereas it actually returns `Promise<undefined>` (since we are doing some loading here)
- Also `create(...)` returns a Proxy in reality so it should be `Proxy<Datastore>` (or just `Datastore` that's fine too I guess)

**Comment by samdenty99** [comment]
Thanks for the feedback. I've fixed all the above issues you've mentioned (and also added the `updatedAt` and `createdAt` types to the documents.)

Something the could be improved is the JSDoc annotations

ie. Changing stuff like

```ts
  /**
   * Insert a document or documents.
   *
   * It's basically the same as the original:
   * https://github.com/louischatriot/nedb#inserting-documents
   *
   * @param  {Object|Object[]} docs
   * @return {Promise.<Object|Object[]>}
   */
```

to 

```ts
  /**
   * Inserts a single document or array of documents into the store.
   * Returns a promise with the resulting documents
   */
```

**Comment by samdenty99** [comment]
@bajankristof Are you still wanting to merge this in? or should I submit it to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by Ricki-BumbleDev** [comment]
Any news on this?

**Comment by AngryPowman** [comment]
Will it merge?

**Comment by bajankristof** [comment]
Hi everyone! Sorry that I kept all of you waiting for so long... I have been busy.
The day has come when I merge this into the source!
Have fun and sorry again!

**Pull request merged**
